server:
  port: 8080
  servlet:
    context-path: /

# 数据源配置
spring:
  # 连接池配置
  datasource:
    url: jdbc:mysql://localhost:3306/sky_music?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置连接超时时间
    connectTimeout: 30000
    # 配置网络超时时间
    socketTimeout: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: true
    filter:
      stat:
        enabled: true
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    # 驼峰映射表字段
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    # 懒加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-aliases-package: com.sky.system.entity #设置别名
  global-config:
    db-config:
      id-type: auto
