USE sky_music;

DROP TABLE IF EXISTS song;
CREATE TABLE song (
	song_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '歌曲ID',
	singer_id BIGINT UNSIGNED NOT NULL COMMENT '歌曲歌手ID',
	album_id BIGINT UNSIGNED NOT NULL COMMENT '歌曲专辑ID',
	song_name VARCHAR(30) NOT NULL COMMENT '歌曲名称',
	song_source VARCHAR(30) COMMENT '歌曲出处',
	is_deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (song_id)
)ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS singer;
CREATE TABLE singer (
	singer_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '歌手ID',
	singer_name VARCHAR(30) NOT NULL DEFAULT '佚名' COMMENT '歌手姓名',
	# singer_profile_id bigint unsigned not null comment '歌手简介ID',
	# singer_profile_image_id bigint unsigned not null comment '歌手头像ID',
	is_deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (singer_id)
)ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS song_singer;
CREATE TABLE song_singer (
	song_id BIGINT UNSIGNED NOT NULL COMMENT '歌曲ID',
	singer_id BIGINT UNSIGNED NOT NULL COMMENT '歌手ID',
	is_deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (song_id, singer_id)
)ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS album;
CREATE TABLE album (
	album_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '专辑ID',
	album_name VARCHAR(30) NOT NULL DEFAULT '无' COMMENT '专辑名',
	is_deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (album_id)
)ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS song_album;
CREATE TABLE song_album (
	song_id BIGINT UNSIGNED NOT NULL COMMENT '歌曲ID',
	album_id BIGINT UNSIGNED NOT NULL COMMENT '专辑ID',
	is_deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (song_id, album_id)
)